spring:
  datasource:
    url: jdbc:mysql://mustafakacar.com.tr:3306/mustaf90_jobbud
    username: mustaf90_jobbud
    password: jobbud_pS
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      javax:
        persistence:
          validation:
            mode: none
server:
  port: 8080


