google-api-key: ${google-api-key}

spring:
  mvc:
    log-request-details: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${google-client-id}
            client-secret: ${google-client-secret}
            scope: openid,profile,email,https://www.googleapis.com/auth/youtube.readonly
            redirect-uri: ${google-redirect-uri}

  datasource:
    url: ${db-datasource-url}
    username: ${db-username}
    password: ${db-password}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      javax:
        persistence:
          validation:
            mode: none

  main:
    allow-bean-definition-overriding: true
  server:
    port: 8080
  config:
    import: optional:file:.env[.properties]


logging:
  level:
    com.springframework.security: DEBUG

jobbud.app.secret: postyAppVerySecretKeyAndItHasToKeepToBe0001
jobbud.expires.in: 360000
refresh.token.expires.in: 6048000
