
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${google-client-id}
            client-secret: ${google-client-secret}
            scope: openid,profile,email,https://www.googleapis.com/auth/youtube.readonly
            redirect-uri: http://localhost:8080/api/v1.0/microtransactions/oauth2/youtube/callback
  datasource:
    url: ${db-datasource-url}
    username: ${db-username}
    password: ${db-password}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      javax:
        persistence:
          validation:
            mode: none

  main:
    allow-bean-definition-overriding: true
  server:
    port: 8080
  config:
    import: optional:file:.env[.properties]


logging:
  level:
    com.springframework.security: TRACE
    org.springframework.security.oauth2: TRACE
    org.springframework.web: TRACE


jobbud.app.secret: jobBudVerySecretKeyAndItHasToKeepToBe0001
jobbud.expires.in: 36000000
refresh.token.expires.in: 604800
